version: '3.8'
services:
  order:
    build: .
    ports:
      - "3001:3001"
    environment:
      - DATA_SOURCE_URL=root:mysql@tcp(localhost:3306)/payment?charset=utf8mb4&parseTime=True&loc=Local
      - APPLICATION_PORT=3001
      - ENV=development
    depends_on:
      - paymentdb
      
  paymentdb:
    image: mysql:8.0
    container_name: paymentdb
    environment:
      - MYSQL_ROOT_PASSWORD=mysql # Contraseña para el usuario root
      - MYSQL_DATABASE=order # Nombre de la base de datos a crear
      - MYSQL_USER=mysql          # Nuevo usuario (no root)
      - MYSQL_PASSWORD=mysql      # Contraseña para el nuevo usuario
    ports:
      - "3306:3306" # Cambiado a puerto predeterminado de MySQL
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5